version: '2'
services:
  app:
    container_name: yourls_app
    build:
      dockerfile: Dockerfile/app
      context: .
    ports:
      - "80:80"
    volumes:
      - ./YOURLS:/srv/app/:rw
      - ./apache/apache2.conf:/etc/apache2/apache2.conf:ro
      - ./apache/ports.conf:/etc/apache2/ports.conf:ro
      - ./apache/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
    links:
      - mysql
    depends_on:
      - mysql
    env_file: .env
    restart: always
  mysql:
    container_name: yourls_db
    image: mysql:5.6
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./databases/mysql/data/:/var/lib/mysql
    restart: always
